name: Generate Version

on:
  workflow_call:
    outputs:
      version:
        description: Release version
        value: ${{ jobs.generate.outputs.version }}

jobs:
  generate:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.extract-version.outputs.version }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node v24
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - id: extract-version
        name: Extract next semantic-release version
        env:
          RELEASE_BRANCHES: '[{"name":"main"},{"name":"dev","prerelease":"dev"}]'
        run: |
          IS_RELEASE="${{ startsWith(github.ref_name, 'release/') }}"
          if [[ "${IS_RELEASE}" == 'true' ]]; then
            GH_TOKEN=${{ secrets.GITHUB_TOKEN }} npx semantic-release --branches "$RELEASE_BRANCHES" --debug --dry-run --verbose > release-temp.log
          else
            GH_TOKEN=${{ secrets.GITHUB_TOKEN }} npx semantic-release --branches "$RELEASE_BRANCHES" --debug --dry-run --verbose > release-temp.log
          fi
          cat release-temp.log
          echo "version=$(cat release-temp.log | grep -oiP 'the next release version is \K.*')" >> "$GITHUB_OUTPUT"

      - name: Release version - ${{ steps.extract-version.outputs.version }}
        run: echo "Next release version - ${{ steps.extract-version.outputs.version }}"
