name: Publish Release Notes

on:
  workflow_call:

jobs:
  publish-release-notes:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js 24.10.0
        uses: actions/setup-node@v3
        with:
          node-version: "24.10.0"

      - id: run-semantic-release
        env:
          RELEASE_BRANCHES: |
            [
              {"name":"main"},
              {"name":"dev","prerelease":"dev"},
              {"name":"${{ github.ref_name }}","prerelease":"rc"}
            ]
        run: |
          IS_RELEASE="${{ startsWith(github.ref_name, 'release/') }}"
          if [[ "${IS_RELEASE}" == 'true' ]]; then
            GH_TOKEN=${{ secrets.GITHUB_TOKEN }} npx semantic-release --branches ${{ env.RELEASE_BRANCHES }} --debug --verbose
          else
            GH_TOKEN=${{ secrets.GITHUB_TOKEN }} npx semantic-release --debug --verbose
          fi
